project:
  type: website
  output-dir: docs

website:
  title: "Shan"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Résumé"
        href: resume.qmd
      - text: "Strategic Marketing"
        href: strategic-marketing.qmd
      - text: "Project Reveal.js"
        href: Project Reveal.js.qmd

format:
  html:
    theme:
      light: 
        - litera
        - theme.scss
      dark: darkly
    css: styles.css   
    toc: true
    page-layout: full
    html-math-method: katex
    include-after-body:
      text: |
        <script>
          function summerYes() {
            document.getElementById("summer-answer").innerHTML =
              "🎉 Let the sunshine, snacks, and sleep-ins begin!";
          }

          function summerNo() {
            document.getElementById("summer-answer").innerHTML =
              "😅 No worries — summer has a way of growing on you.";
          }
        </script>
